name: cht_meteo

channels:
  - conda-forge

dependencies:
  - black
  - build
  - mypy
  - pip
  - pip:
    - git+https://github.com/Deltares/cht_cyclones.git
  - numpy
  - scipy
  - siphon
  - xarray
  - pyproj
  - metpy
  - netCDF4
  - pandas
  - geopandas
  - shapely
  - yaml
  - pytest
  - python=3.10
  - twine
