name: cht_meteo

channels:
  - conda-forge

dependencies:
  - black
  - build
  - mypy
  - pip
  - numpy
  - scipy
  - siphon
  - xarray
  - pyproj
  - metpy
  - pandas
  - pytest
  - toml
  - tomli
  - netCDF4
  - cht_utils
  - pre_commit
  - python=3.10
