name: cht_meteo

channels:
  - conda-forge

dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - xarray
  - pyproj
  - metpy
  - siphon
  - netCDF4

  # Development tools
  - black
  - mypy
  - pytest
  - pre_commit
  - python-build     # ← conda name, not "build"
  - pip

  # Pip-only packages
  - pip:
      - cht_utils

